#!/usr/bin/env node
/**
 * Intellicore — 팀 전용 AI IDE 하네스 설치 스크립트
 *
 * Kiro (.kiro/) 와 Claude (.claude/) 모두 지원
 *
 * Usage:
 *   node install.js <profile> [options]
 *
 *   node install.js cxnexus-backend                          # Kiro + Claude 모두 설치
 *   node install.js cxnexus-backend --ide kiro               # Kiro만
 *   node install.js cxnexus-backend --ide claude             # Claude만
 *   node install.js cxnexus-backend --target /path/to/project
 *   node install.js --list                                   # 프로필 목록
 *   node install.js --status                                 # 설치 상태
 *   node install.js --clean                                  # 제거
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname);
const PROFILES = JSON.parse(fs.readFileSync(path.join(ROOT, 'profiles', 'profiles.json'), 'utf-8')).profiles;

// ── Helpers ──

function copyDir(src, dest) {
  if (!fs.existsSync(src)) return 0;
  fs.mkdirSync(dest, { recursive: true });
  let count = 0;
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) { count += copyDir(s, d); }
    else { fs.copyFileSync(s, d); count++; }
  }
  return count;
}

function parseArgs(argv) {
  const args = { profile: null, target: process.cwd(), ide: 'both' };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--target' && argv[i + 1]) { args.target = path.resolve(argv[++i]); }
    else if (argv[i] === '--ide' && argv[i + 1]) { args.ide = argv[++i]; }
    else if (!argv[i].startsWith('-')) { args.profile = argv[i]; }
  }
  return args;
}

// ── Kiro 설치 ──

function installKiro(profile, profileDef, targetRoot) {
  const kiroDir = path.join(targetRoot, '.kiro');
  let count = 0;

  // steering 규칙 복사
  for (const ruleDir of profileDef.rules) {
    count += copyDir(path.join(ROOT, 'rules', ruleDir), path.join(kiroDir, 'steering'));
  }

  // hooks 복사
  count += copyDir(path.join(ROOT, 'hooks', 'kiro'), path.join(kiroDir, 'hooks'));

  // hooks 내 테스트 커맨드 치환
  const testHook = path.join(kiroDir, 'hooks', 'test-after-task.kiro.hook');
  if (fs.existsSync(testHook)) {
    let content = fs.readFileSync(testHook, 'utf-8');
    content = content.replace(/\.\/gradlew test|npm test|pytest/g, profileDef.testCommand);
    fs.writeFileSync(testHook, content);
  }

  // diagnostics hook — 파일 패턴 치환
  const diagHook = path.join(kiroDir, 'hooks', 'diagnostics-on-save.kiro.hook');
  if (fs.existsSync(diagHook)) {
    let content = fs.readFileSync(diagHook, 'utf-8');
    const patternMap = {
      'kiro-java': '*.java',
      'kiro-ts': '*.ts", "*.tsx',
      'kiro-python': '*.py'
    };
    const pat = patternMap[profileDef.hooks] || '*.java';
    content = content.replace(/"patterns":\s*\[.*?\]/s, `"patterns": ["${pat}"]`);

    const langMap = { 'kiro-java': 'Java', 'kiro-ts': 'TypeScript', 'kiro-python': 'Python' };
    const lang = langMap[profileDef.hooks] || 'Java';
    content = content.replace(/A (Java|TypeScript|Python) file/g, `A ${lang} file`);
    fs.writeFileSync(diagHook, content);
  }

  // settings 복사
  count += copyDir(path.join(ROOT, 'settings'), path.join(kiroDir, 'settings'));

  // 매니페스트 기록
  fs.writeFileSync(path.join(kiroDir, '.harness-manifest.json'), JSON.stringify({
    source: 'intellicore',
    profile,
    version: '1.0.0',
    installedAt: new Date().toISOString()
  }, null, 2));

  return count;
}

// ── Claude 설치 ──

function installClaude(profile, profileDef, targetRoot) {
  const claudeDir = path.join(targetRoot, '.claude');
  fs.mkdirSync(claudeDir, { recursive: true });

  // 모든 규칙을 하나의 CLAUDE.md로 합침
  let content = `# Intellicore Rules — ${profile}\n\n`;
  content += `> Auto-generated by intellicore. Do not edit directly.\n\n`;

  for (const ruleDir of profileDef.rules) {
    const rulesPath = path.join(ROOT, 'rules', ruleDir);
    if (!fs.existsSync(rulesPath)) continue;
    for (const file of fs.readdirSync(rulesPath).filter(f => f.endsWith('.md')).sort()) {
      content += fs.readFileSync(path.join(rulesPath, file), 'utf-8') + '\n\n---\n\n';
    }
  }

  fs.writeFileSync(path.join(targetRoot, 'CLAUDE.md'), content);

  // Claude settings
  fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify({
    source: 'intellicore',
    profile,
    version: '1.0.0',
    installedAt: new Date().toISOString()
  }, null, 2));

  return 2;
}

// ── Commands ──

function install(args) {
  const { profile, target, ide } = args;
  if (!profile || !PROFILES[profile]) {
    console.log(`❌ 프로필 "${profile || ''}"을 찾을 수 없습니다.`);
    listProfiles();
    process.exit(1);
  }

  const def = PROFILES[profile];
  let total = 0;

  if (ide === 'both' || ide === 'kiro') {
    const n = installKiro(profile, def, target);
    total += n;
    console.log(`  ✅ Kiro (.kiro/) — ${n}개 파일`);
  }
  if (ide === 'both' || ide === 'claude') {
    const n = installClaude(profile, def, target);
    total += n;
    console.log(`  ✅ Claude (CLAUDE.md) — ${n}개 파일`);
  }

  console.log(`\n📦 Intellicore 설치 완료`);
  console.log(`   프로필: ${profile} (${def.description})`);
  console.log(`   대상: ${target}`);
  console.log(`   총 ${total}개 파일\n`);
}

function listProfiles() {
  console.log('\n📋 사용 가능한 프로필:\n');
  for (const [name, def] of Object.entries(PROFILES)) {
    console.log(`  ${name.padEnd(20)} ${def.description}`);
  }
  console.log('');
}

function showStatus(target) {
  for (const [ide, file] of [['Kiro', '.kiro/.harness-manifest.json'], ['Claude', '.claude/settings.json']]) {
    const fp = path.join(target, file);
    if (fs.existsSync(fp)) {
      const m = JSON.parse(fs.readFileSync(fp, 'utf-8'));
      console.log(`  ✅ ${ide}: ${m.profile} (${m.installedAt})`);
    } else {
      console.log(`  ❌ ${ide}: 미설치`);
    }
  }
}

function clean(target) {
  let removed = 0;
  // Kiro
  const manifest = path.join(target, '.kiro', '.harness-manifest.json');
  if (fs.existsSync(manifest)) {
    // steering, hooks만 제거 (settings/lsp.json은 유지)
    for (const dir of ['steering', 'hooks']) {
      const d = path.join(target, '.kiro', dir);
      if (fs.existsSync(d)) {
        for (const f of fs.readdirSync(d)) { fs.unlinkSync(path.join(d, f)); removed++; }
      }
    }
    fs.unlinkSync(manifest);
    removed++;
  }
  // Claude
  const claudeMd = path.join(target, 'CLAUDE.md');
  if (fs.existsSync(claudeMd)) { fs.unlinkSync(claudeMd); removed++; }
  const claudeSettings = path.join(target, '.claude', 'settings.json');
  if (fs.existsSync(claudeSettings)) { fs.unlinkSync(claudeSettings); removed++; }

  console.log(removed > 0 ? `\n🗑️  제거 완료 (${removed}개)\n` : '\n❌ 설치된 하네스 없음\n');
}

// ── Main ──

const argv = process.argv.slice(2);

if (argv.includes('--list') || argv.includes('-l')) { listProfiles(); }
else if (argv.includes('--status')) { showStatus(parseArgs(argv).target); }
else if (argv.includes('--clean')) { clean(parseArgs(argv).target); }
else if (argv.includes('--help') || argv.includes('-h') || argv.length === 0) {
  console.log(`
Intellicore — 팀 전용 AI IDE 하네스

Usage:
  node install.js <profile>                        Kiro + Claude 모두 설치
  node install.js <profile> --ide kiro             Kiro만 설치
  node install.js <profile> --ide claude           Claude만 설치
  node install.js <profile> --target /path         지정 경로에 설치
  node install.js --list                           프로필 목록
  node install.js --status                         설치 상태 확인
  node install.js --clean                          하네스 제거
  `);
} else {
  install(parseArgs(argv));
}
